---
name: Docker Image CI
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAMESPACE: nolte
      IMAGE_NAME: mosquitto-exporter

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to Docker Registry
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Determine tag
        run: |
          echo "::set-env name=IMAGE_TAG::${GITHUB_REF#refs/tags/}"

      - name: Build and push container image
        run: |
          docker buildx build \
          -t "${IMAGE_NAMESPACE}/${IMAGE_NAME}:latest" \
          -t "${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}" \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -f Dockerfile \
          .