name: goreleaser

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # TODO: Better cicd implementation!
      - name: build exporter
        run: |
          make generate

