name: e2e-tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v1
        id: installkubectl
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.4.0' # default is latest stable
        id: install
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.0.0

      - run: |
          helm install \
            mosquitto \
            mosquitto \
            -n mosquitto \
            --create-namespace \
            --repo https://k8s-at-home.com/charts/ \
            --wait
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          kubectl apply -k ./k8s/overlays/kind -n mosquitto