name: e2e-tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.0.0

      - name: Helm Deploy
        uses: vimeda/helm@v1.6.1
        with:
          release: 'mosquitto'
          namespace: 'default'
          repo: https://k8s-at-home.com/charts/
          chart: 'mosquitto'
          token: '${{ github.token }}'
          values: |
            name: foobar
        env:
          KUBECONFIG_FILE: "$HOME/.kube/config"